# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4849803eadfdbcefd48c1e1eda8e5303104e10e8d53194bd93096492036bb5d66c47e82dca0c06f8729782d729ac602e53c965d2a209dde2750aaecb7bf1185

test:
  secret_key_base: 702efe5456ba76604c293ab5333c53007908135184daca5eb2c6f39ce07158a69ebd63964e1f214b00b1547cd21ed657fdb36d2b53195304a6ad19b424fa897d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
